"""empty message

Revision ID: 805a2dcc14cb
Revises: f85e6b910db9
Create Date: 2025-09-07 11:40:24.628577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805a2dcc14cb'
down_revision = 'f85e6b910db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_item_order_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_item_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_item_pkey'))
    )
    # ### end Alembic commands ###
